const tableMockData = {
    'id': ['2023-06-05 05:39:33_ɪꜱʜᴀQ ꜱᴀᴡᴋᴀʀ@Mishaqsawkar_twitter',
        '2023-06-05 05:53:23_செந்தமிழன் நவீன் குமார்@naveenkrd_twitter',
        '2023-06-05 06:03:56_Tamil Selvam@tamilvetri84_twitter',
        '2023-06-05 06:40:04_fezamfazil@fezamfazil_twitter',
        '2023-06-05 06:41:34_fezamfazil@fezamfazil_twitter',
        '2023-06-05 06:51:56_Demon Valak@demonvalak42_twitter',
        '2023-06-05 07:42:59_TV9 Kannada@tv9kannada_twitter',
        '2023-06-05 09:23:23_BMTC@BMTC_BENGALURU_twitter',
        '2023-06-05 09:27:17_BMTC@BMTC_BENGALURU_twitter',
        '2023-06-05 09:59:20_BMTC@BMTC_BENGALURU_twitter',
        '2023-06-05 10:35:04_BMTC@BMTC_BENGALURU_twitter',
        '2023-06-05 10:36:41_BMTC@BMTC_BENGALURU_twitter',
        '2023-06-05 10:37:50_BMTC@BMTC_BENGALURU_twitter',
        '2023-06-05 10:38:26_BMTC@BMTC_BENGALURU_twitter',
        '2023-06-05 10:39:01_BMTC@BMTC_BENGALURU_twitter',
        '2023-06-05 11:23:58_PublicTV@publictvnews_twitter',
        '2023-06-05 11:25:20_Udaya Kumar M@udayamaster17_twitter',
        '2023-06-05 11:53:38_Mahesh vc @maheshvvc_twitter',
        '2023-06-05 11:59:18_Parthiv@parthiv_parekh_twitter',
        '2023-06-05 12:59:14_Kamasani Revanth@kamasanirevanth_twitter',
        '2023-06-05 13:02:26_ಬೆಂಗಳೂರು ಸಂಚಾರ ಪೊಲೀಸ್ BengaluruTrafficPolice@blrcitytraffic_twitter',
        '2023-06-05 13:13:23_J T Thribhuvan Kumar@jt_3bhu1_twitter',
        '2023-06-05 13:50:21_BGK office@BGKOffice_twitter',
        '2023-06-05 13:50:25_TV9 Kannada@tv9kannada_twitter',
        '2023-06-05 14:06:08_Navayuga News@NavayugaNews_twitter',
        '2023-06-05 14:28:40_Gopi Smm@gopi_smm_twitter',
        '2023-06-05 15:42:45_Rakesh Ningthoujam@RakeshNingthjam_twitter',
        '2023-06-05 16:43:58_Mahendra@mahebs18_twitter',
        '2023-06-05 16:48:02_Azeemulla Baig@Azeem_ulla_baig_twitter',
        '2023-06-05 17:23:44_Descrypt@descrypthq_twitter',
        '2023-06-05 21:02:35_Bharath Nayaka@BharathNayaka8_twitter',
        '2023-06-06 02:01:14_ASHOK@ashok_pollachi_twitter',
        '2023-06-06 02:02:45_Vimal Shankar.N@VimalShankarN1_twitter',
        '2023-06-06 06:07:28_BMTC@BMTC_BENGALURU_twitter',
        '2023-06-06 07:10:21_Shripad Annigeri@AnnigeriShripad_twitter',
        '2023-06-06 08:13:59_Om Tiwari@tiwxrii_twitter',
        '2023-06-06 10:13:21_raghavendra.badannav@raghavendrabad8_twitter',
        '2023-06-06 10:34:48_Vinod@Hogshead22_twitter',
        '2023-06-06 11:13:16_vinayks0317@gmail.com@vinayks0317_twitter',
        '2023-06-06 12:30:01_North BangalorePost@nBangalorepost_twitter',
        '2023-06-06 13:06:11_VKP@VKP87403207_twitter',
        '2023-06-06 14:28:17_Vinay R@Vinayr56372782_twitter',
        '2023-06-06 15:32:59_Prajavani@prajavani_twitter',
        '2023-06-06 15:51:07_Nneeraj Agrawal@neerajagr1_twitter',
        '2023-06-06 17:43:55_Nneeraj Agrawal@neerajagr1_twitter',
        '2023-06-07 00:36:38_Yes, We Exist @YesWeExistIndia_twitter',
        '2023-06-07 03:36:33_Saikiran Rao@saikiranblore_twitter',
        '2023-06-07 03:45:08_subham mishra@subhammishra152_twitter',
        '2023-06-07 04:10:10_Tisony@Tisony07_twitter',
        '2023-06-07 04:19:58_Shaurii_s@shauryanaditya_twitter',
        '2023-06-07 04:41:11_adhavan@adhvavavan_twitter',
        '2023-06-07 04:45:57_Arjun chilly@Arju936_twitter',
        '2023-06-07 05:34:10_Baljeetkaur@btslove70000_twitter',
        '2023-06-07 05:46:44_concernedcitizen@concern13161846_twitter',
        '2023-06-07 06:15:14_Satheesh@AmilineniS_twitter',
        '2023-06-07 06:19:56_concernedcitizen@concern13161846_twitter',
        '2023-06-07 06:29:25_Sanātanī @patriot_saffron_twitter',
        '2023-06-07 07:32:45_Nneeraj Agrawal@neerajagr1_twitter'
    ],
    'Date': ['2023-06-05 05:39:33',
        '2023-06-05 05:53:23',
        '2023-06-05 06:03:56',
        '2023-06-05 06:40:04',
        '2023-06-05 06:41:34',
        '2023-06-05 06:51:56',
        '2023-06-05 07:42:59',
        '2023-06-05 09:23:23',
        '2023-06-05 09:27:17',
        '2023-06-05 09:59:20',
        '2023-06-05 10:35:04',
        '2023-06-05 10:36:41',
        '2023-06-05 10:37:50',
        '2023-06-05 10:38:26',
        '2023-06-05 10:39:01',
        '2023-06-05 11:23:58',
        '2023-06-05 11:25:20',
        '2023-06-05 11:53:38',
        '2023-06-05 11:59:18',
        '2023-06-05 12:59:14',
        '2023-06-05 13:02:26',
        '2023-06-05 13:13:23',
        '2023-06-05 13:50:21',
        '2023-06-05 13:50:25',
        '2023-06-05 14:06:08',
        '2023-06-05 14:28:40',
        '2023-06-05 15:42:45',
        '2023-06-05 16:43:58',
        '2023-06-05 16:48:02',
        '2023-06-05 17:23:44',
        '2023-06-05 21:02:35',
        '2023-06-06 02:01:14',
        '2023-06-06 02:02:45',
        '2023-06-06 06:07:28',
        '2023-06-06 07:10:21',
        '2023-06-06 08:13:59',
        '2023-06-06 10:13:21',
        '2023-06-06 10:34:48',
        '2023-06-06 11:13:16',
        '2023-06-06 12:30:01',
        '2023-06-06 13:06:11',
        '2023-06-06 14:28:17',
        '2023-06-06 15:32:59',
        '2023-06-06 15:51:07',
        '2023-06-06 17:43:55',
        '2023-06-07 00:36:38',
        '2023-06-07 03:36:33',
        '2023-06-07 03:45:08',
        '2023-06-07 04:10:10',
        '2023-06-07 04:19:58',
        '2023-06-07 04:41:11',
        '2023-06-07 04:45:57',
        '2023-06-07 05:34:10',
        '2023-06-07 05:46:44',
        '2023-06-07 06:15:14',
        '2023-06-07 06:19:56',
        '2023-06-07 06:29:25',
        '2023-06-07 07:32:45'
    ],
    'Intent': ['Others',
        'Appeal/Complaint/Request',
        'Urgent Actionable',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Others',
        'Appeal/Complaint/Request',
        'Others',
        'Others',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Others',
        'Others',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Others',
        'Others',
        'Appeal/Complaint/Request',
        'Others',
        'Appeal/Complaint/Request',
        'Others',
        'Others',
        'Appeal/Complaint/Request',
        'Others',
        'Others',
        'Appeal/Complaint/Request',
        'Others',
        'Appeal/Complaint/Request',
        'Others',
        'Others',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Urgent Actionable',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Others',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Others',
        'Urgent Actionable',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Appeal/Complaint/Request',
        'Others'
    ],
    'Sentiment': ['Neutral',
        'Neutral',
        'Neutral',
        'Negative',
        'Negative',
        'Neutral',
        'Neutral',
        'Neutral',
        'Neutral',
        'Neutral',
        'Neutral',
        'Others',
        'Others',
        'Neutral',
        'Neutral',
        'Neutral',
        'Neutral',
        'Others',
        'Negative',
        'Neutral',
        'Neutral',
        'Neutral',
        'Neutral',
        'Neutral',
        'Neutral',
        'Neutral',
        'Positive',
        'Neutral',
        'Neutral',
        'Neutral',
        'Negative',
        'Neutral',
        'Neutral',
        'Others',
        'Others',
        'Neutral',
        'Neutral',
        'Neutral',
        'Neutral',
        'Positive',
        'Negative',
        'Negative',
        'Neutral',
        'Neutral',
        'Negative',
        'Neutral',
        'Negative',
        'Negative',
        'Neutral',
        'Negative',
        'Neutral',
        'Negative',
        'Neutral',
        'Negative',
        'Neutral',
        'Negative',
        'Negative',
        'Others'
    ],
    'Sub_Class': ['',
        'Ticket printing issue',
        'Digital and Manual board Issue',
        'Women issue',
        'Women issue',
        'Vehicle Defect',
        'Others',
        'Crew misbehavior',
        '',
        'Others',
        'Vehicle Defect',
        '',
        'Ticket printing issue',
        'Ticket printing issue',
        'Ticket printing issue',
        'Others',
        '',
        '',
        'Vehicle Defect',
        'Digital and Manual board Issue',
        'Others',
        'Others',
        'Digital and Manual board Issue',
        'Others',
        'Others',
        'Route deviation',
        'Others',
        'Cleanliness Of vehicle',
        'Vehicle Defect',
        'Partial Trip',
        'Digital and Manual board Issue',
        'Q R  code issue',
        'Vehicle Defect',
        '',
        'Others',
        'Route deviation',
        'Others',
        'Cleanliness Of vehicle',
        'Others',
        'Partial Trip',
        '',
        'Others',
        '',
        'Others',
        'Others',
        'Cleanliness Of vehicle',
        'Cleanliness Of vehicle',
        'Checking Issue',
        'Others',
        'Others',
        'Crew misbehavior',
        'Crew misbehavior',
        'Mobile app related',
        'Others',
        'Koramangala TTMC',
        'Crew misbehavior',
        '',
        ''
    ],
    'Super_Class': ['Others',
        'Ticket Related Issue',
        'Vehicle Related Issue',
        'Crew Behaviors',
        'Crew Behaviors',
        'Vehicle Related Issue',
        'Vehicle Related Issue',
        'Crew Behaviors',
        'Others',
        'Ticket Related Issue',
        'Vehicle Related Issue',
        'Others',
        'Ticket Related Issue',
        'Ticket Related Issue',
        'Ticket Related Issue',
        'Vehicle Related Issue',
        'Others',
        'Others',
        'Vehicle Related Issue',
        'Vehicle Related Issue',
        'Vehicle Related Issue',
        'Ticket Related Issue',
        'Vehicle Related Issue',
        'Vehicle Related Issue',
        'Vehicle Related Issue',
        'Route',
        'Crew Behaviors',
        'Vehicle Related Issue',
        'Vehicle Related Issue',
        'Route',
        'Vehicle Related Issue',
        'Ticket Related Issue',
        'Vehicle Related Issue',
        'Others',
        'Vehicle Related Issue',
        'Route',
        'Vehicle Related Issue',
        'Vehicle Related Issue',
        'Facility Issue',
        'Route',
        'Others',
        'Vehicle Related Issue',
        'Others',
        'Vehicle Related Issue',
        'Facility Issue',
        'Vehicle Related Issue',
        'Vehicle Related Issue',
        'Ticket Related Issue',
        'Facility Issue',
        'Vehicle Related Issue',
        'Crew Behaviors',
        'Crew Behaviors',
        'Website/App Related Issue',
        'Vehicle Related Issue',
        'Facility Issue',
        'Crew Behaviors',
        'Others',
        'Others'
    ],
    'user_message': ['What happened is there any update',
        'Thank you for your reply Sir KSRTC is a interstate And intrastate Bus Not BMTC Bangalore city Public Transport and Can you show me the 10 rs Ticket In KSRTC Min Ksrtc Bus fare starts from Rs 250 to 300 Per head Conductor Can t Avoid In the name of Change',
        'Bangalore la Already in QR Code payment in BMTC Bus',
        'A female college student was asked to get down of the bus midway by the conductor for not having a change of 5 rupees The incident happened at 9 40 am today on Bellandur tin factory bus KA 57 F 3022',
        'A female college student was asked to get down of the bus midway by the conductor for not having a change of 5 rupees The incident happened at 9 40 am today on Bellandur tin factory bus KA 57 F 3022',
        '43B Hoskerehalli to Majestic 34 Hoskerehalli to Shivaji Nagar Purple ELECTRIC BUS kodak enn rogga Or BLUE diesel BUS kodak enn rogga',
        '                                KSRTC BMTC FreeBusService bengaluru Siddaramaiah',
        'We will educate the crew in this regard',
        'It will be from June 11th',
        'The said ticket is issued in KIA service as it is a special service the fare chat is different compare to volo service And issued ticket is correct',
        'KIA 4A is being operated from BEML layout to airport',
        'For timing information pl visit our website',
        'BMTC2022007540 is your complaint docket number             ',
        'BMTC2022007541 is your complaint docket number',
        'BMTC2022007542 is your complaint docket number',
        '                           Karnataka BUS FreeBus Bengaluru KSRTC BMTC',
        'This is how we Public Transport behave Bengaluru bmtc nammabengaluru bengalurudiaries Karnataka bangalorelife silkboard bangalorebus',
        '                                                ',
        'Bus driver was rash driving and the attached picture is at Chickpet signal The bus no is KA01F8742 He was driving completely left and when he had to enter majestic he suddenly moved towards right without looking at the vehicles and I had to apply sudden brakes',
        'Hey What are those displays installed in the vajra bus do you know',
        '         5                         BMTC                                       ',
        'As far as I know KSRTC or BMTC fares have not gone up from the time Assembly elections were declared Only increase in electricity tariff were announced after the election ie 13th May 2023 but before Siddu DKS were sworn alongwith 8 cabinet Ministers',
        '    Its already implemented BMTC da venna',
        '                    RamalingaReddy karnatakatransportcorporation KSRTC BMTC NWKRTC KKRTC',
        '                                          ministerramalingareddy TransportMinister KarnatakaGovernment bengalore BTMLayout KSRTC BMTC nwksrtc kkrtc',
        'Ada loosu payale bmtc le epovo introduce pantanga',
        'Mad respect for the BMTC bus drivers The fact that they can drive in Bengaluru traffic safely is pure skill',
        'BMTC included but no 50 seat reservation',
        'BS 6 blue buses are',
        'Similar vibes in Bangalore Between BMTC Metro and a little bit of walking 1 2KM at most you can cover most of the city And what s more Metro coverage is going to more than double in next 2 3 years',
        'This BMTC only send docket number but don t take any action against they do only send text after few days later action taken against them complaint solved that s it do nothing i have given complaint not stopping bus in our sto p Kaniminike colony bidadi depot but no one cares',
        'Ticket as usual given by conductor only This qr is only for payment of bus fare digitally instead of paying using physical money It s available in BMTC buses for quite some time and it s seamless',
        'BMTC already done uruttu saambu mavanae TNSTC kondu vandha nalla irukum',
        '',
        'Pls Correct and make them uniform Pls let us know how many BMTC used buses are alloted to Dharwad City depot',
        'Sir all these things are ok but ladies ge bmtc ali free madidira gents yen taap maddru sir Gender equality na',
        'What about bmtc local private buses For me no one auto drivers lotted as of now If they lotted u thn can raise a complaint to concern dept',
        'There are no pink buses in KA Women can travel in any ordinary KSRTC or BMTC bus It is free No need to wait for pink bus only',
        'Ok sir please ask congress to regularize the jobs of ksrtc and bmtc workers too Many of them in this department don t get salaries and increments on time how will they take care of there families They too are poor',
        'Shakti Smart Cards offer women the opportunity to travel for free on from Jun 11 onwards Register on Sevasindhu portal to avail Bengaluru BMTC KSRTC Bangalore freetravel karnataka',
        'BMTC connectivity is worst nobody can say what time your bus will be at stop missing night time 2 3 empty buses cover the route in gap of less than a min Payment mode nobody know bad behavior of staff raining inside bus need more reason',
        'Ranganath sir if free passes are issued to Women to use BMTC then what is the point in extending metro lines and Railways while people choose to use BMTC and KSRTC Crores of money spent on construction of metro goes in vain',
        '                          bmtc',
        'this is the scene whole day at hope farm No cop to monitor these rogue buses In this hot weather we have to wait long at signals',
        'Sir its not happening and not effective Officers sitting in their comfotable offices are being reported wrongly Pls spend time on spot by surprise and then comment I see it everyday Its becoming worse day by day',
        'KSRTC BMTC NWKRT and KKRTC buses are covered Inter state travel AC Sleeper Luxury buses not covered',
        'First thing they need to do is increase atleast 500 1000 buses immediately during peak mornings n evenings Horrible scenarios to witness across the city Ppl barely able to stand n crushed inside the bus Feels like are we still living in the 80s 90s era',
        'Without any reason they are stopping the bus we are getting delay to office i asked reason to conductor they saying for ticket we had stopped the bus by running bus also they can cut ticket but what s the reason they are stopping the bus No kA01FA4558',
        'plz ask all companies in Bangalore to opt for mass transit like and provide transportation to employees Everyone is forced to go to office each one drives car traffic is becoming hell Take action',
        'I also see red light rules being broken at 6 or 7 a m daily near Nexa showroom KDP Building Near Forum Mall Suddagunte Palya Adugodi on a daily basis even by buses and camera being useless Someone can ask me to sit and make many videos I wake up early',
        'Bus conductors of are demanding to study Human packing structures Squeeze Close Packing SCP is no longer enough on busy routes s',
        'Conductor pushing to passenger and avoiding to admit to the Bus He saying you can go and complaint where you want and God Grace my friend was saved otherwise he got injury May be very dangerous experience with BMTC coming days Depot no 19',
        'please tell us if we need to register anywhere for free rides for women Are these for all or only for Karnataka women s',
        '1 of the main problems with Hebbal junction will come from extreme left and use their size to bulldoze to go below flyover making all others behind to be stuck they pass by easily sir plz look into it will never respond',
        'Big craters below flyover on Ring Road at Tannisandra Cross can those be filled asap Even BMTC bus drivers try to avoid those craters',
        'Very true They ve become this way only due to no action taken by for any violation they do They ve been given a free hand to go rogue on the city and no one will touch them So they ve become goondas now',
        'now tell me a beautiful lie about increase in BMTC prices increase in property taxes and fuel prices too this is a perfect example of how these chamchas will be USED as a to justify congress s corruption',
        'For ur info n action'
    ]
}
export default tableMockData;